### PR TITLE
(WIP) PayU rest API payment provider with recurring payments

### PR DESCRIPTION
**Pull request by PetrDlouhy**
This adds PayU payment provider with support of recurring payments.

The code is mostly complete and working, although some polishing might be needed. I would appreciate any feedback to my changes.

### CODE REVIEW

**Comment by patrys** [comment]
Would you mind submitting Tox/Travis changes as a separate PR? I would merge those immediately while the other changes might need some discussion.

**Comment by Mrooie** [comment]
Hi @patrys @PetrDlouhy!
Is that PR safe to install when I need just PayU payments to be processed? :D

**Comment by PetrDlouhy** [comment]
@Mrooie The code is mostly feature complete, you should be able to make payments with this.

I am still working on this, so I cannot yet guarantee, that I don't introduce some changes, that will mean some extra work for you when migrating to them.

Also, the code didn't undergo any review at all, so there might be some security problems, that I overlooked.

Anyway, I would appreciate any help with this, especially testing and code review.

**Comment by patrys** [comment]
I suggest creating a separate `django-payments-payu` repository for the actual gateway implementation (we can link to it from the repository readme but our team can't support all possible gateways) and submitting a PR with just the changes required in the core.

**Comment by Mrooie** [comment]
@PetrDlouhy Thanks!
I guess I'm a bit affraid to make any changes by myself, but I can do testing when you are ready :D

**Comment by PetrDlouhy** [comment]
@patrys OK, I will do that. The biggest downside of that I see is, that the compatibility with `django-payments` will not be tested on every change of `django-payments` by Travis.

**Comment by patrys** [comment]
That's true but you can configure Travis to automatically test your repository against the master branch of `django-payments` on a daily basis. This way you'll get a notification if the gateway code needs to be updated (or you can yell at us for introducing a bug 😄).

**Pull request closed without merging**
