### PR TITLE
Update project URL

### PR DESCRIPTION
**Pull request by WhyNotHugo**
This PR will also test CI and coverage integration.

### CODE REVIEW

**Review by patrys — APPROVED** [review]

**Comment by jezdez** [comment]
@patrys Could you force-push a change to this to trigger Travis again?

**Comment by WhyNotHugo** [comment]
Codecov has run, but doesn't seem to be reporting here. Maybe it needs permissions?

https://codecov.io/gh/jazzband/django-payments

**Comment by jezdez** [comment]
@WhyNotHugo I'm not sure to be honest, my guess is that Codecov is still working through the repo changes on their side. I have all permissions set up correctly and there is no Codecov specific config file here that would prevent the PR checks to be created. Let's keep an eye on it and see if it fixes itself first..

**Comment by jezdez** [comment]
We should maybe try this in a new PR?

**Pull request merged**
