### PR TITLE
Update RTD config for v2

### PR DESCRIPTION
**Pull request by hugovk**
For https://github.com/jazzband/help/issues/276.

Following docs at https://docs.readthedocs.io/en/stable/config-file/v2.html

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
Any ideas why CI is not running for this PR?

**Review by WhyNotHugo — APPROVED** [review]
LGTM

**Comment by hugovk** [comment]
> Any ideas why CI is not running for this PR?

```yaml
on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, synchronize, reopened]
```

It's not running on the `push` because that's done only on `main`.

I'm not sure why it's not running on `pull_request`, those look like valid types:

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

I recommend keeping the config simple:


```yml
on: [push, pull_request, workflow_dispatch]
```

This allows feature branches to be tested, and `workflow_dispatch` also adds a button to the UI to allow triggering a build (like with Travis).

**Comment by hugovk** [comment]
Hmm, docs build failed again: https://readthedocs.org/projects/django-payments/builds/16387829/

> Problem in your project's configuration. Parse error in .readthedocs.yaml: YAML: mapping values are not allowed here in "<unicode string>", line 12, column 25: extra_requirements: ^

I'll enable RTD in my branch and try again!

**Comment by hugovk** [comment]
@WhyNotHugo Great, you got it working!

* https://github.com/jazzband/django-payments/commit/b755a348869037465a038c44f49199d8a1911692
* https://readthedocs.org/projects/django-payments/builds/16387904/
* https://django-payments-hugovk.readthedocs.io/en/latest/

**Comment by WhyNotHugo** [comment]
Thanks for the help!

**Pull request merged**
