### PR TITLE
Update changelog for new supported Python/Django

### PR DESCRIPTION
**Pull request by WhyNotHugo**
See https://github.com/jazzband/django-payments/pull/347

### CODE REVIEW

**Comment by jezdez** [comment]
@WhyNotHugo I just triggered a rebase from main to try out the RTD PR integration from #355 here

**Review by mariofix — APPROVED** [review]

**Comment by mariofix** [comment]
I think that's it with the review.

Hey @WhyNotHugo I read your other message, I would like to get in touch, I'm @mariofix in most networks, let me know where we can chat to make the proper introductions.

**Comment by WhyNotHugo** [comment]
RTD is working fine for this: https://django-payments--348.org.readthedocs.build/en/348/

**Comment by WhyNotHugo** [comment]
@mariofix I'm whynothugo in most places. I'm on libera.chat or telegram or signal, whatever works for you :)

**Pull request merged**
