### PR TITLE
updated classifiers

### PR DESCRIPTION
**Pull request by anukaal**
added support for python 3.10

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
We should also:
- Update `tox.ini` to run tests with Python 3.10.
- Update `.githhub/workflows/test.yml` to run CI with 3.10.
- Add a CHANGELOG entry.

**Review by WhyNotHugo — CHANGES_REQUESTED** [review]
Thanks. We should also:
- Update `tox.ini` to run tests with Python 3.10.
- Update `.githhub/workflows/test.yml` to run CI with 3.10.
- Add a CHANGELOG entry v0.15.1.

**Review by WhyNotHugo — APPROVED** [review]
Thanks! :beers:

**Comment by anukaal** [comment]
> Thanks! 🍻

Thanks for the guidance

**Pull request merged**
