### PR TITLE
Use only required fields in stripe js

### PR DESCRIPTION
**Pull request by artursmet**
Stripe doesn't require address, to create card token: https://stripe.com/docs/api#create_card_token

### CODE REVIEW

**Comment by patrys** [comment]
@mociepka?

**Comment by mociepka** [comment]
It doesn't require it but you can provide them. Management from stripe account will be simpler with all data.

**Comment by artursmet** [comment]
In my opinion we shouldn't force to provide address data. There are checkout systems, collecting only basic data like email and credit card details. It'll be more universal I think

**Comment by patrys** [comment]
Can you provide screenshots of before and after? Can we somehow send the data that we have to Stripe without prompting the user?

**Comment by artursmet** [comment]
With address data, stripe does some additional checks I think:

With data:
stripe_with_data


Without:
stripe_without_data


But it looks like 'Street check` and 'Zip check` are not so strict (passed with Polish zip code and US as a country)

**Comment by mariofix** [comment]
stale

**Pull request closed without merging**
